/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BugsReportRouteImport } from './routes/bugs/report'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/signup/index'
import { Route as AuthenticatedPlusIndexRouteImport } from './routes/_authenticated/plus/index'
import { Route as AuthenticatedOnboardingIndexRouteImport } from './routes/_authenticated/onboarding/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthSignupVerifyEmailRouteImport } from './routes/auth/signup/verify-email'
import { Route as AuthSignupSuccessRouteImport } from './routes/auth/signup/success'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings/profile'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedPlusSuccessRouteImport } from './routes/_authenticated/plus/success'
import { Route as AuthenticatedDashboardProjectsRouteImport } from './routes/_authenticated/dashboard/projects'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard/profile'
import { Route as AuthenticatedDashboardIssuesRouteImport } from './routes/_authenticated/dashboard/issues'
import { Route as AuthenticatedDashboardIntegrationsRouteImport } from './routes/_authenticated/dashboard/integrations'
import { Route as AuthenticatedDashboardExceptionsRouteImport } from './routes/_authenticated/dashboard/exceptions'
import { Route as AuthenticatedDashboardEventsRouteImport } from './routes/_authenticated/dashboard/events'
import { Route as AuthenticatedSettingsOrganizationIndexRouteImport } from './routes/_authenticated/settings/organization/index'
import { Route as AuthenticatedDashboardChatIndexRouteImport } from './routes/_authenticated/dashboard/chat/index'
import { Route as AuthenticatedSettingsOrganizationBillingRouteImport } from './routes/_authenticated/settings/organization/billing'
import { Route as AuthenticatedDashboardProjectsNewRouteImport } from './routes/_authenticated/dashboard/projects_/new'
import { Route as AuthenticatedDashboardChatChatIdRouteImport } from './routes/_authenticated/dashboard/chat/$chatId'
import { Route as AuthenticatedDashboardUptimeMonitorsIndexRouteImport } from './routes/_authenticated/dashboard/uptime/monitors/index'
import { Route as AuthenticatedDashboardUptimeIncidentsIndexRouteImport } from './routes/_authenticated/dashboard/uptime/incidents/index'
import { Route as AuthenticatedDashboardIssuesIssueIdIndexRouteImport } from './routes/_authenticated/dashboard/issues_/$issueId/index'
import { Route as AuthenticatedDashboardUptimeMonitorsNewRouteImport } from './routes/_authenticated/dashboard/uptime/monitors/new'
import { Route as AuthenticatedDashboardProjectsProjectIdSettingsRouteImport } from './routes/_authenticated/dashboard/projects_/$projectId/settings'
import { Route as AuthenticatedDashboardUptimeMonitorsMonitorIdIndexRouteImport } from './routes/_authenticated/dashboard/uptime/monitors/$monitorId/index'
import { Route as AuthenticatedDashboardUptimeIncidentsIncidentIdIndexRouteImport } from './routes/_authenticated/dashboard/uptime/incidents/$incidentId/index'
import { Route as AuthenticatedDashboardIssuesIssueIdExceptionsIndexRouteImport } from './routes/_authenticated/dashboard/issues_/$issueId/exceptions/index'
import { Route as AuthenticatedDashboardIntegrationsAwsWafIndexRouteImport } from './routes/_authenticated/dashboard/integrations_/aws/waf/index'
import { Route as AuthenticatedDashboardIssuesIssueIdExceptionsExceptionIdRouteImport } from './routes/_authenticated/dashboard/issues_/$issueId/exceptions/$exceptionId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BugsReportRoute = BugsReportRouteImport.update({
  id: '/bugs/report',
  path: '/bugs/report',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/auth/signup/',
  path: '/auth/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlusIndexRoute = AuthenticatedPlusIndexRouteImport.update({
  id: '/plus/',
  path: '/plus/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingIndexRoute =
  AuthenticatedOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthSignupVerifyEmailRoute = AuthSignupVerifyEmailRouteImport.update({
  id: '/auth/signup/verify-email',
  path: '/auth/signup/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupSuccessRoute = AuthSignupSuccessRouteImport.update({
  id: '/auth/signup/success',
  path: '/auth/signup/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedPlusSuccessRoute =
  AuthenticatedPlusSuccessRouteImport.update({
    id: '/plus/success',
    path: '/plus/success',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardProjectsRoute =
  AuthenticatedDashboardProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardIssuesRoute =
  AuthenticatedDashboardIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardIntegrationsRoute =
  AuthenticatedDashboardIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardExceptionsRoute =
  AuthenticatedDashboardExceptionsRouteImport.update({
    id: '/exceptions',
    path: '/exceptions',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEventsRoute =
  AuthenticatedDashboardEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedSettingsOrganizationIndexRoute =
  AuthenticatedSettingsOrganizationIndexRouteImport.update({
    id: '/organization/',
    path: '/organization/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedDashboardChatIndexRoute =
  AuthenticatedDashboardChatIndexRouteImport.update({
    id: '/chat/',
    path: '/chat/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedSettingsOrganizationBillingRoute =
  AuthenticatedSettingsOrganizationBillingRouteImport.update({
    id: '/organization/billing',
    path: '/organization/billing',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedDashboardProjectsNewRoute =
  AuthenticatedDashboardProjectsNewRouteImport.update({
    id: '/projects_/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardChatChatIdRoute =
  AuthenticatedDashboardChatChatIdRouteImport.update({
    id: '/chat/$chatId',
    path: '/chat/$chatId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardUptimeMonitorsIndexRoute =
  AuthenticatedDashboardUptimeMonitorsIndexRouteImport.update({
    id: '/uptime/monitors/',
    path: '/uptime/monitors/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardUptimeIncidentsIndexRoute =
  AuthenticatedDashboardUptimeIncidentsIndexRouteImport.update({
    id: '/uptime/incidents/',
    path: '/uptime/incidents/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardIssuesIssueIdIndexRoute =
  AuthenticatedDashboardIssuesIssueIdIndexRouteImport.update({
    id: '/issues_/$issueId/',
    path: '/issues/$issueId/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardUptimeMonitorsNewRoute =
  AuthenticatedDashboardUptimeMonitorsNewRouteImport.update({
    id: '/uptime/monitors/new',
    path: '/uptime/monitors/new',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProjectsProjectIdSettingsRoute =
  AuthenticatedDashboardProjectsProjectIdSettingsRouteImport.update({
    id: '/projects_/$projectId/settings',
    path: '/projects/$projectId/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardUptimeMonitorsMonitorIdIndexRoute =
  AuthenticatedDashboardUptimeMonitorsMonitorIdIndexRouteImport.update({
    id: '/uptime/monitors/$monitorId/',
    path: '/uptime/monitors/$monitorId/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardUptimeIncidentsIncidentIdIndexRoute =
  AuthenticatedDashboardUptimeIncidentsIncidentIdIndexRouteImport.update({
    id: '/uptime/incidents/$incidentId/',
    path: '/uptime/incidents/$incidentId/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardIssuesIssueIdExceptionsIndexRoute =
  AuthenticatedDashboardIssuesIssueIdExceptionsIndexRouteImport.update({
    id: '/issues_/$issueId/exceptions/',
    path: '/issues/$issueId/exceptions/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardIntegrationsAwsWafIndexRoute =
  AuthenticatedDashboardIntegrationsAwsWafIndexRouteImport.update({
    id: '/integrations_/aws/waf/',
    path: '/integrations/aws/waf/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardIssuesIssueIdExceptionsExceptionIdRoute =
  AuthenticatedDashboardIssuesIssueIdExceptionsExceptionIdRouteImport.update({
    id: '/issues_/$issueId/exceptions/$exceptionId',
    path: '/issues/$issueId/exceptions/$exceptionId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/bugs/report': typeof BugsReportRoute
  '/dashboard/events': typeof AuthenticatedDashboardEventsRoute
  '/dashboard/exceptions': typeof AuthenticatedDashboardExceptionsRoute
  '/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsRoute
  '/dashboard/issues': typeof AuthenticatedDashboardIssuesRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/projects': typeof AuthenticatedDashboardProjectsRoute
  '/plus/success': typeof AuthenticatedPlusSuccessRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/auth/signup/success': typeof AuthSignupSuccessRoute
  '/auth/signup/verify-email': typeof AuthSignupVerifyEmailRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/plus': typeof AuthenticatedPlusIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/dashboard/chat/$chatId': typeof AuthenticatedDashboardChatChatIdRoute
  '/dashboard/projects/new': typeof AuthenticatedDashboardProjectsNewRoute
  '/settings/organization/billing': typeof AuthenticatedSettingsOrganizationBillingRoute
  '/dashboard/chat': typeof AuthenticatedDashboardChatIndexRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationIndexRoute
  '/dashboard/projects/$projectId/settings': typeof AuthenticatedDashboardProjectsProjectIdSettingsRoute
  '/dashboard/uptime/monitors/new': typeof AuthenticatedDashboardUptimeMonitorsNewRoute
  '/dashboard/issues/$issueId': typeof AuthenticatedDashboardIssuesIssueIdIndexRoute
  '/dashboard/uptime/incidents': typeof AuthenticatedDashboardUptimeIncidentsIndexRoute
  '/dashboard/uptime/monitors': typeof AuthenticatedDashboardUptimeMonitorsIndexRoute
  '/dashboard/issues/$issueId/exceptions/$exceptionId': typeof AuthenticatedDashboardIssuesIssueIdExceptionsExceptionIdRoute
  '/dashboard/integrations/aws/waf': typeof AuthenticatedDashboardIntegrationsAwsWafIndexRoute
  '/dashboard/issues/$issueId/exceptions': typeof AuthenticatedDashboardIssuesIssueIdExceptionsIndexRoute
  '/dashboard/uptime/incidents/$incidentId': typeof AuthenticatedDashboardUptimeIncidentsIncidentIdIndexRoute
  '/dashboard/uptime/monitors/$monitorId': typeof AuthenticatedDashboardUptimeMonitorsMonitorIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/bugs/report': typeof BugsReportRoute
  '/dashboard/events': typeof AuthenticatedDashboardEventsRoute
  '/dashboard/exceptions': typeof AuthenticatedDashboardExceptionsRoute
  '/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsRoute
  '/dashboard/issues': typeof AuthenticatedDashboardIssuesRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/projects': typeof AuthenticatedDashboardProjectsRoute
  '/plus/success': typeof AuthenticatedPlusSuccessRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/auth/signup/success': typeof AuthSignupSuccessRoute
  '/auth/signup/verify-email': typeof AuthSignupVerifyEmailRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/plus': typeof AuthenticatedPlusIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/dashboard/chat/$chatId': typeof AuthenticatedDashboardChatChatIdRoute
  '/dashboard/projects/new': typeof AuthenticatedDashboardProjectsNewRoute
  '/settings/organization/billing': typeof AuthenticatedSettingsOrganizationBillingRoute
  '/dashboard/chat': typeof AuthenticatedDashboardChatIndexRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationIndexRoute
  '/dashboard/projects/$projectId/settings': typeof AuthenticatedDashboardProjectsProjectIdSettingsRoute
  '/dashboard/uptime/monitors/new': typeof AuthenticatedDashboardUptimeMonitorsNewRoute
  '/dashboard/issues/$issueId': typeof AuthenticatedDashboardIssuesIssueIdIndexRoute
  '/dashboard/uptime/incidents': typeof AuthenticatedDashboardUptimeIncidentsIndexRoute
  '/dashboard/uptime/monitors': typeof AuthenticatedDashboardUptimeMonitorsIndexRoute
  '/dashboard/issues/$issueId/exceptions/$exceptionId': typeof AuthenticatedDashboardIssuesIssueIdExceptionsExceptionIdRoute
  '/dashboard/integrations/aws/waf': typeof AuthenticatedDashboardIntegrationsAwsWafIndexRoute
  '/dashboard/issues/$issueId/exceptions': typeof AuthenticatedDashboardIssuesIssueIdExceptionsIndexRoute
  '/dashboard/uptime/incidents/$incidentId': typeof AuthenticatedDashboardUptimeIncidentsIncidentIdIndexRoute
  '/dashboard/uptime/monitors/$monitorId': typeof AuthenticatedDashboardUptimeMonitorsMonitorIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/bugs/report': typeof BugsReportRoute
  '/_authenticated/dashboard/events': typeof AuthenticatedDashboardEventsRoute
  '/_authenticated/dashboard/exceptions': typeof AuthenticatedDashboardExceptionsRoute
  '/_authenticated/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsRoute
  '/_authenticated/dashboard/issues': typeof AuthenticatedDashboardIssuesRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/projects': typeof AuthenticatedDashboardProjectsRoute
  '/_authenticated/plus/success': typeof AuthenticatedPlusSuccessRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/auth/signup/success': typeof AuthSignupSuccessRoute
  '/auth/signup/verify-email': typeof AuthSignupVerifyEmailRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/_authenticated/plus/': typeof AuthenticatedPlusIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/_authenticated/dashboard/chat/$chatId': typeof AuthenticatedDashboardChatChatIdRoute
  '/_authenticated/dashboard/projects_/new': typeof AuthenticatedDashboardProjectsNewRoute
  '/_authenticated/settings/organization/billing': typeof AuthenticatedSettingsOrganizationBillingRoute
  '/_authenticated/dashboard/chat/': typeof AuthenticatedDashboardChatIndexRoute
  '/_authenticated/settings/organization/': typeof AuthenticatedSettingsOrganizationIndexRoute
  '/_authenticated/dashboard/projects_/$projectId/settings': typeof AuthenticatedDashboardProjectsProjectIdSettingsRoute
  '/_authenticated/dashboard/uptime/monitors/new': typeof AuthenticatedDashboardUptimeMonitorsNewRoute
  '/_authenticated/dashboard/issues_/$issueId/': typeof AuthenticatedDashboardIssuesIssueIdIndexRoute
  '/_authenticated/dashboard/uptime/incidents/': typeof AuthenticatedDashboardUptimeIncidentsIndexRoute
  '/_authenticated/dashboard/uptime/monitors/': typeof AuthenticatedDashboardUptimeMonitorsIndexRoute
  '/_authenticated/dashboard/issues_/$issueId/exceptions/$exceptionId': typeof AuthenticatedDashboardIssuesIssueIdExceptionsExceptionIdRoute
  '/_authenticated/dashboard/integrations_/aws/waf/': typeof AuthenticatedDashboardIntegrationsAwsWafIndexRoute
  '/_authenticated/dashboard/issues_/$issueId/exceptions/': typeof AuthenticatedDashboardIssuesIssueIdExceptionsIndexRoute
  '/_authenticated/dashboard/uptime/incidents/$incidentId/': typeof AuthenticatedDashboardUptimeIncidentsIncidentIdIndexRoute
  '/_authenticated/dashboard/uptime/monitors/$monitorId/': typeof AuthenticatedDashboardUptimeMonitorsMonitorIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/bugs/report'
    | '/dashboard/events'
    | '/dashboard/exceptions'
    | '/dashboard/integrations'
    | '/dashboard/issues'
    | '/dashboard/profile'
    | '/dashboard/projects'
    | '/plus/success'
    | '/settings/account'
    | '/settings/profile'
    | '/auth/signup/success'
    | '/auth/signup/verify-email'
    | '/dashboard/'
    | '/onboarding'
    | '/plus'
    | '/auth/signup'
    | '/dashboard/chat/$chatId'
    | '/dashboard/projects/new'
    | '/settings/organization/billing'
    | '/dashboard/chat'
    | '/settings/organization'
    | '/dashboard/projects/$projectId/settings'
    | '/dashboard/uptime/monitors/new'
    | '/dashboard/issues/$issueId'
    | '/dashboard/uptime/incidents'
    | '/dashboard/uptime/monitors'
    | '/dashboard/issues/$issueId/exceptions/$exceptionId'
    | '/dashboard/integrations/aws/waf'
    | '/dashboard/issues/$issueId/exceptions'
    | '/dashboard/uptime/incidents/$incidentId'
    | '/dashboard/uptime/monitors/$monitorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/bugs/report'
    | '/dashboard/events'
    | '/dashboard/exceptions'
    | '/dashboard/integrations'
    | '/dashboard/issues'
    | '/dashboard/profile'
    | '/dashboard/projects'
    | '/plus/success'
    | '/settings/account'
    | '/settings/profile'
    | '/auth/signup/success'
    | '/auth/signup/verify-email'
    | '/dashboard'
    | '/onboarding'
    | '/plus'
    | '/auth/signup'
    | '/dashboard/chat/$chatId'
    | '/dashboard/projects/new'
    | '/settings/organization/billing'
    | '/dashboard/chat'
    | '/settings/organization'
    | '/dashboard/projects/$projectId/settings'
    | '/dashboard/uptime/monitors/new'
    | '/dashboard/issues/$issueId'
    | '/dashboard/uptime/incidents'
    | '/dashboard/uptime/monitors'
    | '/dashboard/issues/$issueId/exceptions/$exceptionId'
    | '/dashboard/integrations/aws/waf'
    | '/dashboard/issues/$issueId/exceptions'
    | '/dashboard/uptime/incidents/$incidentId'
    | '/dashboard/uptime/monitors/$monitorId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/bugs/report'
    | '/_authenticated/dashboard/events'
    | '/_authenticated/dashboard/exceptions'
    | '/_authenticated/dashboard/integrations'
    | '/_authenticated/dashboard/issues'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/projects'
    | '/_authenticated/plus/success'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/profile'
    | '/auth/signup/success'
    | '/auth/signup/verify-email'
    | '/_authenticated/dashboard/'
    | '/_authenticated/onboarding/'
    | '/_authenticated/plus/'
    | '/auth/signup/'
    | '/_authenticated/dashboard/chat/$chatId'
    | '/_authenticated/dashboard/projects_/new'
    | '/_authenticated/settings/organization/billing'
    | '/_authenticated/dashboard/chat/'
    | '/_authenticated/settings/organization/'
    | '/_authenticated/dashboard/projects_/$projectId/settings'
    | '/_authenticated/dashboard/uptime/monitors/new'
    | '/_authenticated/dashboard/issues_/$issueId/'
    | '/_authenticated/dashboard/uptime/incidents/'
    | '/_authenticated/dashboard/uptime/monitors/'
    | '/_authenticated/dashboard/issues_/$issueId/exceptions/$exceptionId'
    | '/_authenticated/dashboard/integrations_/aws/waf/'
    | '/_authenticated/dashboard/issues_/$issueId/exceptions/'
    | '/_authenticated/dashboard/uptime/incidents/$incidentId/'
    | '/_authenticated/dashboard/uptime/monitors/$monitorId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  BugsReportRoute: typeof BugsReportRoute
  AuthSignupSuccessRoute: typeof AuthSignupSuccessRoute
  AuthSignupVerifyEmailRoute: typeof AuthSignupVerifyEmailRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bugs/report': {
      id: '/bugs/report'
      path: '/bugs/report'
      fullPath: '/bugs/report'
      preLoaderRoute: typeof BugsReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/plus/': {
      id: '/_authenticated/plus/'
      path: '/plus'
      fullPath: '/plus'
      preLoaderRoute: typeof AuthenticatedPlusIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/': {
      id: '/_authenticated/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/auth/signup/verify-email': {
      id: '/auth/signup/verify-email'
      path: '/auth/signup/verify-email'
      fullPath: '/auth/signup/verify-email'
      preLoaderRoute: typeof AuthSignupVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup/success': {
      id: '/auth/signup/success'
      path: '/auth/signup/success'
      fullPath: '/auth/signup/success'
      preLoaderRoute: typeof AuthSignupSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/plus/success': {
      id: '/_authenticated/plus/success'
      path: '/plus/success'
      fullPath: '/plus/success'
      preLoaderRoute: typeof AuthenticatedPlusSuccessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/projects': {
      id: '/_authenticated/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof AuthenticatedDashboardProjectsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/issues': {
      id: '/_authenticated/dashboard/issues'
      path: '/issues'
      fullPath: '/dashboard/issues'
      preLoaderRoute: typeof AuthenticatedDashboardIssuesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/integrations': {
      id: '/_authenticated/dashboard/integrations'
      path: '/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof AuthenticatedDashboardIntegrationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/exceptions': {
      id: '/_authenticated/dashboard/exceptions'
      path: '/exceptions'
      fullPath: '/dashboard/exceptions'
      preLoaderRoute: typeof AuthenticatedDashboardExceptionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/events': {
      id: '/_authenticated/dashboard/events'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof AuthenticatedDashboardEventsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/settings/organization/': {
      id: '/_authenticated/settings/organization/'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/dashboard/chat/': {
      id: '/_authenticated/dashboard/chat/'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof AuthenticatedDashboardChatIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/settings/organization/billing': {
      id: '/_authenticated/settings/organization/billing'
      path: '/organization/billing'
      fullPath: '/settings/organization/billing'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationBillingRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/dashboard/projects_/new': {
      id: '/_authenticated/dashboard/projects_/new'
      path: '/projects/new'
      fullPath: '/dashboard/projects/new'
      preLoaderRoute: typeof AuthenticatedDashboardProjectsNewRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/chat/$chatId': {
      id: '/_authenticated/dashboard/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/dashboard/chat/$chatId'
      preLoaderRoute: typeof AuthenticatedDashboardChatChatIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/uptime/monitors/': {
      id: '/_authenticated/dashboard/uptime/monitors/'
      path: '/uptime/monitors'
      fullPath: '/dashboard/uptime/monitors'
      preLoaderRoute: typeof AuthenticatedDashboardUptimeMonitorsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/uptime/incidents/': {
      id: '/_authenticated/dashboard/uptime/incidents/'
      path: '/uptime/incidents'
      fullPath: '/dashboard/uptime/incidents'
      preLoaderRoute: typeof AuthenticatedDashboardUptimeIncidentsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/issues_/$issueId/': {
      id: '/_authenticated/dashboard/issues_/$issueId/'
      path: '/issues/$issueId'
      fullPath: '/dashboard/issues/$issueId'
      preLoaderRoute: typeof AuthenticatedDashboardIssuesIssueIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/uptime/monitors/new': {
      id: '/_authenticated/dashboard/uptime/monitors/new'
      path: '/uptime/monitors/new'
      fullPath: '/dashboard/uptime/monitors/new'
      preLoaderRoute: typeof AuthenticatedDashboardUptimeMonitorsNewRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/projects_/$projectId/settings': {
      id: '/_authenticated/dashboard/projects_/$projectId/settings'
      path: '/projects/$projectId/settings'
      fullPath: '/dashboard/projects/$projectId/settings'
      preLoaderRoute: typeof AuthenticatedDashboardProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/uptime/monitors/$monitorId/': {
      id: '/_authenticated/dashboard/uptime/monitors/$monitorId/'
      path: '/uptime/monitors/$monitorId'
      fullPath: '/dashboard/uptime/monitors/$monitorId'
      preLoaderRoute: typeof AuthenticatedDashboardUptimeMonitorsMonitorIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/uptime/incidents/$incidentId/': {
      id: '/_authenticated/dashboard/uptime/incidents/$incidentId/'
      path: '/uptime/incidents/$incidentId'
      fullPath: '/dashboard/uptime/incidents/$incidentId'
      preLoaderRoute: typeof AuthenticatedDashboardUptimeIncidentsIncidentIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/issues_/$issueId/exceptions/': {
      id: '/_authenticated/dashboard/issues_/$issueId/exceptions/'
      path: '/issues/$issueId/exceptions'
      fullPath: '/dashboard/issues/$issueId/exceptions'
      preLoaderRoute: typeof AuthenticatedDashboardIssuesIssueIdExceptionsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/integrations_/aws/waf/': {
      id: '/_authenticated/dashboard/integrations_/aws/waf/'
      path: '/integrations/aws/waf'
      fullPath: '/dashboard/integrations/aws/waf'
      preLoaderRoute: typeof AuthenticatedDashboardIntegrationsAwsWafIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/issues_/$issueId/exceptions/$exceptionId': {
      id: '/_authenticated/dashboard/issues_/$issueId/exceptions/$exceptionId'
      path: '/issues/$issueId/exceptions/$exceptionId'
      fullPath: '/dashboard/issues/$issueId/exceptions/$exceptionId'
      preLoaderRoute: typeof AuthenticatedDashboardIssuesIssueIdExceptionsExceptionIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardEventsRoute: typeof AuthenticatedDashboardEventsRoute
  AuthenticatedDashboardExceptionsRoute: typeof AuthenticatedDashboardExceptionsRoute
  AuthenticatedDashboardIntegrationsRoute: typeof AuthenticatedDashboardIntegrationsRoute
  AuthenticatedDashboardIssuesRoute: typeof AuthenticatedDashboardIssuesRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardProjectsRoute: typeof AuthenticatedDashboardProjectsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardChatChatIdRoute: typeof AuthenticatedDashboardChatChatIdRoute
  AuthenticatedDashboardProjectsNewRoute: typeof AuthenticatedDashboardProjectsNewRoute
  AuthenticatedDashboardChatIndexRoute: typeof AuthenticatedDashboardChatIndexRoute
  AuthenticatedDashboardProjectsProjectIdSettingsRoute: typeof AuthenticatedDashboardProjectsProjectIdSettingsRoute
  AuthenticatedDashboardUptimeMonitorsNewRoute: typeof AuthenticatedDashboardUptimeMonitorsNewRoute
  AuthenticatedDashboardIssuesIssueIdIndexRoute: typeof AuthenticatedDashboardIssuesIssueIdIndexRoute
  AuthenticatedDashboardUptimeIncidentsIndexRoute: typeof AuthenticatedDashboardUptimeIncidentsIndexRoute
  AuthenticatedDashboardUptimeMonitorsIndexRoute: typeof AuthenticatedDashboardUptimeMonitorsIndexRoute
  AuthenticatedDashboardIssuesIssueIdExceptionsExceptionIdRoute: typeof AuthenticatedDashboardIssuesIssueIdExceptionsExceptionIdRoute
  AuthenticatedDashboardIntegrationsAwsWafIndexRoute: typeof AuthenticatedDashboardIntegrationsAwsWafIndexRoute
  AuthenticatedDashboardIssuesIssueIdExceptionsIndexRoute: typeof AuthenticatedDashboardIssuesIssueIdExceptionsIndexRoute
  AuthenticatedDashboardUptimeIncidentsIncidentIdIndexRoute: typeof AuthenticatedDashboardUptimeIncidentsIncidentIdIndexRoute
  AuthenticatedDashboardUptimeMonitorsMonitorIdIndexRoute: typeof AuthenticatedDashboardUptimeMonitorsMonitorIdIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardEventsRoute: AuthenticatedDashboardEventsRoute,
    AuthenticatedDashboardExceptionsRoute:
      AuthenticatedDashboardExceptionsRoute,
    AuthenticatedDashboardIntegrationsRoute:
      AuthenticatedDashboardIntegrationsRoute,
    AuthenticatedDashboardIssuesRoute: AuthenticatedDashboardIssuesRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardProjectsRoute: AuthenticatedDashboardProjectsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardChatChatIdRoute:
      AuthenticatedDashboardChatChatIdRoute,
    AuthenticatedDashboardProjectsNewRoute:
      AuthenticatedDashboardProjectsNewRoute,
    AuthenticatedDashboardChatIndexRoute: AuthenticatedDashboardChatIndexRoute,
    AuthenticatedDashboardProjectsProjectIdSettingsRoute:
      AuthenticatedDashboardProjectsProjectIdSettingsRoute,
    AuthenticatedDashboardUptimeMonitorsNewRoute:
      AuthenticatedDashboardUptimeMonitorsNewRoute,
    AuthenticatedDashboardIssuesIssueIdIndexRoute:
      AuthenticatedDashboardIssuesIssueIdIndexRoute,
    AuthenticatedDashboardUptimeIncidentsIndexRoute:
      AuthenticatedDashboardUptimeIncidentsIndexRoute,
    AuthenticatedDashboardUptimeMonitorsIndexRoute:
      AuthenticatedDashboardUptimeMonitorsIndexRoute,
    AuthenticatedDashboardIssuesIssueIdExceptionsExceptionIdRoute:
      AuthenticatedDashboardIssuesIssueIdExceptionsExceptionIdRoute,
    AuthenticatedDashboardIntegrationsAwsWafIndexRoute:
      AuthenticatedDashboardIntegrationsAwsWafIndexRoute,
    AuthenticatedDashboardIssuesIssueIdExceptionsIndexRoute:
      AuthenticatedDashboardIssuesIssueIdExceptionsIndexRoute,
    AuthenticatedDashboardUptimeIncidentsIncidentIdIndexRoute:
      AuthenticatedDashboardUptimeIncidentsIncidentIdIndexRoute,
    AuthenticatedDashboardUptimeMonitorsMonitorIdIndexRoute:
      AuthenticatedDashboardUptimeMonitorsMonitorIdIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsOrganizationBillingRoute: typeof AuthenticatedSettingsOrganizationBillingRoute
  AuthenticatedSettingsOrganizationIndexRoute: typeof AuthenticatedSettingsOrganizationIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsOrganizationBillingRoute:
    AuthenticatedSettingsOrganizationBillingRoute,
  AuthenticatedSettingsOrganizationIndexRoute:
    AuthenticatedSettingsOrganizationIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedPlusSuccessRoute: typeof AuthenticatedPlusSuccessRoute
  AuthenticatedOnboardingIndexRoute: typeof AuthenticatedOnboardingIndexRoute
  AuthenticatedPlusIndexRoute: typeof AuthenticatedPlusIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedPlusSuccessRoute: AuthenticatedPlusSuccessRoute,
  AuthenticatedOnboardingIndexRoute: AuthenticatedOnboardingIndexRoute,
  AuthenticatedPlusIndexRoute: AuthenticatedPlusIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  BugsReportRoute: BugsReportRoute,
  AuthSignupSuccessRoute: AuthSignupSuccessRoute,
  AuthSignupVerifyEmailRoute: AuthSignupVerifyEmailRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
