/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/signup/index'
import { Route as AuthenticatedOnboardingIndexRouteImport } from './routes/_authenticated/onboarding/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthSignupVerifyEmailRouteImport } from './routes/auth/signup/verify-email'
import { Route as AuthSignupSuccessRouteImport } from './routes/auth/signup/success'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedDashboardProjectsRouteImport } from './routes/_authenticated/dashboard/projects'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard/profile'
import { Route as AuthenticatedDashboardIssuesRouteImport } from './routes/_authenticated/dashboard/issues'
import { Route as AuthenticatedDashboardIntegrationsRouteImport } from './routes/_authenticated/dashboard/integrations'
import { Route as AuthenticatedDashboardExceptionsRouteImport } from './routes/_authenticated/dashboard/exceptions'
import { Route as AuthenticatedDashboardEventsRouteImport } from './routes/_authenticated/dashboard/events'
import { Route as AuthenticatedDashboardChatIndexRouteImport } from './routes/_authenticated/dashboard/chat/index'
import { Route as AuthenticatedDashboardChatChatIdRouteImport } from './routes/_authenticated/dashboard/chat/$chatId'
import { Route as AuthenticatedDashboardIssuesIssueIdIndexRouteImport } from './routes/_authenticated/dashboard/issues_/$issueId/index'
import { Route as AuthenticatedDashboardProjectsProjectIdSettingsRouteImport } from './routes/_authenticated/dashboard/projects_/$projectId/settings'
import { Route as AuthenticatedDashboardIssuesIssueIdExceptionsIndexRouteImport } from './routes/_authenticated/dashboard/issues_/$issueId/exceptions/index'
import { Route as AuthenticatedDashboardIntegrationsAwsWafIndexRouteImport } from './routes/_authenticated/dashboard/integrations_/aws/waf/index'
import { Route as AuthenticatedDashboardIssuesIssueIdExceptionsExceptionIdRouteImport } from './routes/_authenticated/dashboard/issues_/$issueId/exceptions/$exceptionId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/auth/signup/',
  path: '/auth/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingIndexRoute =
  AuthenticatedOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthSignupVerifyEmailRoute = AuthSignupVerifyEmailRouteImport.update({
  id: '/auth/signup/verify-email',
  path: '/auth/signup/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupSuccessRoute = AuthSignupSuccessRouteImport.update({
  id: '/auth/signup/success',
  path: '/auth/signup/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardProjectsRoute =
  AuthenticatedDashboardProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardIssuesRoute =
  AuthenticatedDashboardIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardIntegrationsRoute =
  AuthenticatedDashboardIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardExceptionsRoute =
  AuthenticatedDashboardExceptionsRouteImport.update({
    id: '/exceptions',
    path: '/exceptions',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEventsRoute =
  AuthenticatedDashboardEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardChatIndexRoute =
  AuthenticatedDashboardChatIndexRouteImport.update({
    id: '/chat/',
    path: '/chat/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardChatChatIdRoute =
  AuthenticatedDashboardChatChatIdRouteImport.update({
    id: '/chat/$chatId',
    path: '/chat/$chatId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardIssuesIssueIdIndexRoute =
  AuthenticatedDashboardIssuesIssueIdIndexRouteImport.update({
    id: '/issues_/$issueId/',
    path: '/issues/$issueId/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProjectsProjectIdSettingsRoute =
  AuthenticatedDashboardProjectsProjectIdSettingsRouteImport.update({
    id: '/projects_/$projectId/settings',
    path: '/projects/$projectId/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardIssuesIssueIdExceptionsIndexRoute =
  AuthenticatedDashboardIssuesIssueIdExceptionsIndexRouteImport.update({
    id: '/issues_/$issueId/exceptions/',
    path: '/issues/$issueId/exceptions/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardIntegrationsAwsWafIndexRoute =
  AuthenticatedDashboardIntegrationsAwsWafIndexRouteImport.update({
    id: '/integrations_/aws/waf/',
    path: '/integrations/aws/waf/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardIssuesIssueIdExceptionsExceptionIdRoute =
  AuthenticatedDashboardIssuesIssueIdExceptionsExceptionIdRouteImport.update({
    id: '/issues_/$issueId/exceptions/$exceptionId',
    path: '/issues/$issueId/exceptions/$exceptionId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/events': typeof AuthenticatedDashboardEventsRoute
  '/dashboard/exceptions': typeof AuthenticatedDashboardExceptionsRoute
  '/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsRoute
  '/dashboard/issues': typeof AuthenticatedDashboardIssuesRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/projects': typeof AuthenticatedDashboardProjectsRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/auth/signup/success': typeof AuthSignupSuccessRoute
  '/auth/signup/verify-email': typeof AuthSignupVerifyEmailRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/dashboard/chat/$chatId': typeof AuthenticatedDashboardChatChatIdRoute
  '/dashboard/chat': typeof AuthenticatedDashboardChatIndexRoute
  '/dashboard/projects/$projectId/settings': typeof AuthenticatedDashboardProjectsProjectIdSettingsRoute
  '/dashboard/issues/$issueId': typeof AuthenticatedDashboardIssuesIssueIdIndexRoute
  '/dashboard/issues/$issueId/exceptions/$exceptionId': typeof AuthenticatedDashboardIssuesIssueIdExceptionsExceptionIdRoute
  '/dashboard/integrations/aws/waf': typeof AuthenticatedDashboardIntegrationsAwsWafIndexRoute
  '/dashboard/issues/$issueId/exceptions': typeof AuthenticatedDashboardIssuesIssueIdExceptionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/events': typeof AuthenticatedDashboardEventsRoute
  '/dashboard/exceptions': typeof AuthenticatedDashboardExceptionsRoute
  '/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsRoute
  '/dashboard/issues': typeof AuthenticatedDashboardIssuesRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/projects': typeof AuthenticatedDashboardProjectsRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/auth/signup/success': typeof AuthSignupSuccessRoute
  '/auth/signup/verify-email': typeof AuthSignupVerifyEmailRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/dashboard/chat/$chatId': typeof AuthenticatedDashboardChatChatIdRoute
  '/dashboard/chat': typeof AuthenticatedDashboardChatIndexRoute
  '/dashboard/projects/$projectId/settings': typeof AuthenticatedDashboardProjectsProjectIdSettingsRoute
  '/dashboard/issues/$issueId': typeof AuthenticatedDashboardIssuesIssueIdIndexRoute
  '/dashboard/issues/$issueId/exceptions/$exceptionId': typeof AuthenticatedDashboardIssuesIssueIdExceptionsExceptionIdRoute
  '/dashboard/integrations/aws/waf': typeof AuthenticatedDashboardIntegrationsAwsWafIndexRoute
  '/dashboard/issues/$issueId/exceptions': typeof AuthenticatedDashboardIssuesIssueIdExceptionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_authenticated/dashboard/events': typeof AuthenticatedDashboardEventsRoute
  '/_authenticated/dashboard/exceptions': typeof AuthenticatedDashboardExceptionsRoute
  '/_authenticated/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsRoute
  '/_authenticated/dashboard/issues': typeof AuthenticatedDashboardIssuesRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/projects': typeof AuthenticatedDashboardProjectsRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/auth/signup/success': typeof AuthSignupSuccessRoute
  '/auth/signup/verify-email': typeof AuthSignupVerifyEmailRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/_authenticated/dashboard/chat/$chatId': typeof AuthenticatedDashboardChatChatIdRoute
  '/_authenticated/dashboard/chat/': typeof AuthenticatedDashboardChatIndexRoute
  '/_authenticated/dashboard/projects_/$projectId/settings': typeof AuthenticatedDashboardProjectsProjectIdSettingsRoute
  '/_authenticated/dashboard/issues_/$issueId/': typeof AuthenticatedDashboardIssuesIssueIdIndexRoute
  '/_authenticated/dashboard/issues_/$issueId/exceptions/$exceptionId': typeof AuthenticatedDashboardIssuesIssueIdExceptionsExceptionIdRoute
  '/_authenticated/dashboard/integrations_/aws/waf/': typeof AuthenticatedDashboardIntegrationsAwsWafIndexRoute
  '/_authenticated/dashboard/issues_/$issueId/exceptions/': typeof AuthenticatedDashboardIssuesIssueIdExceptionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/dashboard/events'
    | '/dashboard/exceptions'
    | '/dashboard/integrations'
    | '/dashboard/issues'
    | '/dashboard/profile'
    | '/dashboard/projects'
    | '/settings/account'
    | '/auth/signup/success'
    | '/auth/signup/verify-email'
    | '/dashboard/'
    | '/onboarding'
    | '/auth/signup'
    | '/dashboard/chat/$chatId'
    | '/dashboard/chat'
    | '/dashboard/projects/$projectId/settings'
    | '/dashboard/issues/$issueId'
    | '/dashboard/issues/$issueId/exceptions/$exceptionId'
    | '/dashboard/integrations/aws/waf'
    | '/dashboard/issues/$issueId/exceptions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/dashboard/events'
    | '/dashboard/exceptions'
    | '/dashboard/integrations'
    | '/dashboard/issues'
    | '/dashboard/profile'
    | '/dashboard/projects'
    | '/settings/account'
    | '/auth/signup/success'
    | '/auth/signup/verify-email'
    | '/dashboard'
    | '/onboarding'
    | '/auth/signup'
    | '/dashboard/chat/$chatId'
    | '/dashboard/chat'
    | '/dashboard/projects/$projectId/settings'
    | '/dashboard/issues/$issueId'
    | '/dashboard/issues/$issueId/exceptions/$exceptionId'
    | '/dashboard/integrations/aws/waf'
    | '/dashboard/issues/$issueId/exceptions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/_authenticated/dashboard/events'
    | '/_authenticated/dashboard/exceptions'
    | '/_authenticated/dashboard/integrations'
    | '/_authenticated/dashboard/issues'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/projects'
    | '/_authenticated/settings/account'
    | '/auth/signup/success'
    | '/auth/signup/verify-email'
    | '/_authenticated/dashboard/'
    | '/_authenticated/onboarding/'
    | '/auth/signup/'
    | '/_authenticated/dashboard/chat/$chatId'
    | '/_authenticated/dashboard/chat/'
    | '/_authenticated/dashboard/projects_/$projectId/settings'
    | '/_authenticated/dashboard/issues_/$issueId/'
    | '/_authenticated/dashboard/issues_/$issueId/exceptions/$exceptionId'
    | '/_authenticated/dashboard/integrations_/aws/waf/'
    | '/_authenticated/dashboard/issues_/$issueId/exceptions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupSuccessRoute: typeof AuthSignupSuccessRoute
  AuthSignupVerifyEmailRoute: typeof AuthSignupVerifyEmailRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding/': {
      id: '/_authenticated/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/auth/signup/verify-email': {
      id: '/auth/signup/verify-email'
      path: '/auth/signup/verify-email'
      fullPath: '/auth/signup/verify-email'
      preLoaderRoute: typeof AuthSignupVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup/success': {
      id: '/auth/signup/success'
      path: '/auth/signup/success'
      fullPath: '/auth/signup/success'
      preLoaderRoute: typeof AuthSignupSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/projects': {
      id: '/_authenticated/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof AuthenticatedDashboardProjectsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/issues': {
      id: '/_authenticated/dashboard/issues'
      path: '/issues'
      fullPath: '/dashboard/issues'
      preLoaderRoute: typeof AuthenticatedDashboardIssuesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/integrations': {
      id: '/_authenticated/dashboard/integrations'
      path: '/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof AuthenticatedDashboardIntegrationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/exceptions': {
      id: '/_authenticated/dashboard/exceptions'
      path: '/exceptions'
      fullPath: '/dashboard/exceptions'
      preLoaderRoute: typeof AuthenticatedDashboardExceptionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/events': {
      id: '/_authenticated/dashboard/events'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof AuthenticatedDashboardEventsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/chat/': {
      id: '/_authenticated/dashboard/chat/'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof AuthenticatedDashboardChatIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/chat/$chatId': {
      id: '/_authenticated/dashboard/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/dashboard/chat/$chatId'
      preLoaderRoute: typeof AuthenticatedDashboardChatChatIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/issues_/$issueId/': {
      id: '/_authenticated/dashboard/issues_/$issueId/'
      path: '/issues/$issueId'
      fullPath: '/dashboard/issues/$issueId'
      preLoaderRoute: typeof AuthenticatedDashboardIssuesIssueIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/projects_/$projectId/settings': {
      id: '/_authenticated/dashboard/projects_/$projectId/settings'
      path: '/projects/$projectId/settings'
      fullPath: '/dashboard/projects/$projectId/settings'
      preLoaderRoute: typeof AuthenticatedDashboardProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/issues_/$issueId/exceptions/': {
      id: '/_authenticated/dashboard/issues_/$issueId/exceptions/'
      path: '/issues/$issueId/exceptions'
      fullPath: '/dashboard/issues/$issueId/exceptions'
      preLoaderRoute: typeof AuthenticatedDashboardIssuesIssueIdExceptionsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/integrations_/aws/waf/': {
      id: '/_authenticated/dashboard/integrations_/aws/waf/'
      path: '/integrations/aws/waf'
      fullPath: '/dashboard/integrations/aws/waf'
      preLoaderRoute: typeof AuthenticatedDashboardIntegrationsAwsWafIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/issues_/$issueId/exceptions/$exceptionId': {
      id: '/_authenticated/dashboard/issues_/$issueId/exceptions/$exceptionId'
      path: '/issues/$issueId/exceptions/$exceptionId'
      fullPath: '/dashboard/issues/$issueId/exceptions/$exceptionId'
      preLoaderRoute: typeof AuthenticatedDashboardIssuesIssueIdExceptionsExceptionIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardEventsRoute: typeof AuthenticatedDashboardEventsRoute
  AuthenticatedDashboardExceptionsRoute: typeof AuthenticatedDashboardExceptionsRoute
  AuthenticatedDashboardIntegrationsRoute: typeof AuthenticatedDashboardIntegrationsRoute
  AuthenticatedDashboardIssuesRoute: typeof AuthenticatedDashboardIssuesRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardProjectsRoute: typeof AuthenticatedDashboardProjectsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardChatChatIdRoute: typeof AuthenticatedDashboardChatChatIdRoute
  AuthenticatedDashboardChatIndexRoute: typeof AuthenticatedDashboardChatIndexRoute
  AuthenticatedDashboardProjectsProjectIdSettingsRoute: typeof AuthenticatedDashboardProjectsProjectIdSettingsRoute
  AuthenticatedDashboardIssuesIssueIdIndexRoute: typeof AuthenticatedDashboardIssuesIssueIdIndexRoute
  AuthenticatedDashboardIssuesIssueIdExceptionsExceptionIdRoute: typeof AuthenticatedDashboardIssuesIssueIdExceptionsExceptionIdRoute
  AuthenticatedDashboardIntegrationsAwsWafIndexRoute: typeof AuthenticatedDashboardIntegrationsAwsWafIndexRoute
  AuthenticatedDashboardIssuesIssueIdExceptionsIndexRoute: typeof AuthenticatedDashboardIssuesIssueIdExceptionsIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardEventsRoute: AuthenticatedDashboardEventsRoute,
    AuthenticatedDashboardExceptionsRoute:
      AuthenticatedDashboardExceptionsRoute,
    AuthenticatedDashboardIntegrationsRoute:
      AuthenticatedDashboardIntegrationsRoute,
    AuthenticatedDashboardIssuesRoute: AuthenticatedDashboardIssuesRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardProjectsRoute: AuthenticatedDashboardProjectsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardChatChatIdRoute:
      AuthenticatedDashboardChatChatIdRoute,
    AuthenticatedDashboardChatIndexRoute: AuthenticatedDashboardChatIndexRoute,
    AuthenticatedDashboardProjectsProjectIdSettingsRoute:
      AuthenticatedDashboardProjectsProjectIdSettingsRoute,
    AuthenticatedDashboardIssuesIssueIdIndexRoute:
      AuthenticatedDashboardIssuesIssueIdIndexRoute,
    AuthenticatedDashboardIssuesIssueIdExceptionsExceptionIdRoute:
      AuthenticatedDashboardIssuesIssueIdExceptionsExceptionIdRoute,
    AuthenticatedDashboardIntegrationsAwsWafIndexRoute:
      AuthenticatedDashboardIntegrationsAwsWafIndexRoute,
    AuthenticatedDashboardIssuesIssueIdExceptionsIndexRoute:
      AuthenticatedDashboardIssuesIssueIdExceptionsIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedOnboardingIndexRoute: typeof AuthenticatedOnboardingIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedOnboardingIndexRoute: AuthenticatedOnboardingIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupSuccessRoute: AuthSignupSuccessRoute,
  AuthSignupVerifyEmailRoute: AuthSignupVerifyEmailRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
